### ISSUE TITLE
I can not get the Python sensor script to work

### ISSUE THREAD

**Issue by jimidak** [instana/python-sensor#188]
There are several module imports that fail.

**Comment by pglombardo** [comment]
Hi @jimidak - I need a little bit more to go on that that :-)

Could you post the error output?

**Comment by jimidak** [comment]
Ha! You are right, that was very vague! But I was kind of intentionally that way. Basically, I'm looking for any help getting the Instana API to work. I'm trying to pull some metrics out of our instanta instance via API calls. I'm trying to follow the API documentation, but running into some snags. I found your python API script and thought that may help my efforts. I am executing against python 3.7. There are several module includes that it can't find. Do you have a use case example for that python script? in other words, should I be able to use it as-is, and import it into my own python and create an instance of that API class?

Thanks for the help

-Rich

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by pglombardo** [comment]
Hi @jimidak sorry for the late response on this.

If you're referring to the Python Rest API client, that unfortunately hasn't been updated to v2 of the API yet.

For better handling & prioritization, could you [file a ticket](https://support.instana.com/hc/en-us/requests/new) so that this issue get the right attention?  This way we can get this resolved ASAP.

Much appreciated.  I'll close this issue for now but let me know if you have any issues opening a ticket.
