### ISSUE TITLE
Check implication of __init__ for rabbitmq span type

### ISSUE THREAD

**Issue by manojpandey** [instana/python-sensor#301]
Specifically this piece of code: https://github.com/instana/python-sensor/blob/f800501fe1259322056bf1f2bbb0516de688e9a7/instana/span.py#L257-L258

```
    def __init__(self, span, source, service_name, **kwargs):
        # pylint: disable=invalid-name
        super(RegisteredSpan, self).__init__(span, source, service_name, **kwargs)
        self.n = span.operation_name
        self.k = 1
        if span.operation_name in self.ENTRY_SPANS:
            # entry
            self._populate_entry_span_data(span)
            self.data["service"] = service_name
        elif span.operation_name in self.EXIT_SPANS:
            self.k = 2 # exit
            self._populate_exit_span_data(span)
        elif span.operation_name in self.LOCAL_SPANS:
            self.k = 3 # intermediate span
            self._populate_local_span_data(span)

        if "rabbitmq" in self.data and self.data["rabbitmq"]["sort"] == "consume":
            self.k = 1  # entry
```

Looks like, it has no effect.

**Comment by andrewslotin** [comment]
@manojpandey, could you verify if the exit RabbitMQ spans have proper kind?

**Comment by pglombardo** [comment]
Because rabbitmq is a dual type span (entry & exit) based on the `sort` key it's registered in both `ENTRY_SPANS` and `EXIT_SPANS`.

So the default exit kind for all spans is 1 (entry):
https://github.com/instana/python-sensor/blob/f800501fe1259322056bf1f2bbb0516de688e9a7/instana/span.py#L245

Then through the `if` statement the exit type condition gets hit (because rabbitmq is a member of `ENTRY_SPANS`):
https://github.com/instana/python-sensor/blob/f800501fe1259322056bf1f2bbb0516de688e9a7/instana/span.py#L250-L252

Then we set it back to `exit` type **if** the `sort` key matches:
https://github.com/instana/python-sensor/blob/f800501fe1259322056bf1f2bbb0516de688e9a7/instana/span.py#L257-L258

The path of the logic is solid although it's not that evident and could possibly be reorganised to be easier to understand.  `rabbitmq` is special case because of the kind duality.

It looks like the tests are not validating the kind type so ideally that should be added to the test runs:
https://github.com/instana/python-sensor/blob/master/tests/clients/test_asynqp.py

**Comment by andrewslotin** [comment]
Hey @pglombardo, great to see you again! I see the point, however the problem is that `rabbitmq` is listed both in `ENTRY_SPANS` and `EXIT_SPANS`, and while processing it we'll hit the branch that uses `_populate_entry_span_data()` and keeps the `self.k` unchanged, so by the time the `if "rabbitmq" in self.data and self.data["rabbitmq"]["sort"] == "consume"` is executed, `self.k` will be still set to `1`.
