### ISSUE TITLE
Is Python 3.10 supported?

### ISSUE THREAD

**Issue by alexlang74** [instana/python-sensor#455]
### Problem Description

The github documentation says "Python > 2.7 is supported", but https://www.ibm.com/docs/en/instana-observability/current?topic=package-python-supported-components-versions#python-runtimes limits this to 
Python < 3.10. 
Which one is correct? If Python 3.10 is not supported yet - do you have a timeline for that?  Thanks!

### Python Version

3.10

### Python Modules

```shell
na
```

### Python Environment

```shell
na
```

**Comment by Ferenc-** [comment]
Hi @alexlang74,

Where have you read on github, that `"Python > 2.7 is supported"` ?
I had the codebase of this repo searched with multiple tools, and none of them could find anything like that on the current `mater` branch head.
If there is such a statement, then let us know, because that is definitely incorrect,
currently the minimum needed runtime verion, for the supported track is `3.7`.

The documentation [here](https://www.ibm.com/docs/en/instana-observability/current?topic=package-python-supported-components-versions#python-runtimes) is correct. Commercial support is only for `< 3.10` at the moment. You can write an [AHA ticket about it](https://bigblue.aha.io/products/INSTANA/ideas_overview), or contact PM, if you want this to be prioritized. 

BTW, if you are not using `asyncio` or `tornado`, then your experience on `3.10` should be comparable to the `3.9`.

**Comment by alexlang74** [comment]
Argh, I mistyped! of course 3.7, sorry! We're using FastAPI on PY 3.10, and want to use instana goodness...

**Comment by Ferenc-** [comment]
> Argh, I mistyped! of course 3.7, sorry! We're using FastAPI on PY 3.10, and want to use instana goodness...

And would you run it on k8s, with the webhook?
Which server would you use with FastAPI? `uvicorn`?

**Comment by alexlang74** [comment]
Thank you!!
